name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: Genez-io/genezio-github-action@main
        with:
          genezio-version: latest
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Workaround to maintain the same subdomain
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.frontend.subdomain = "awesome-purple-capybara"' genezio.yaml
      - name: Deploy
        working-directory: ./server
        run: genezio deploy
